import { Router, Request, Response } from 'express';
import os from 'os';
import { hubClient, hubConfigured } from '../services/hub';
import { saveIdentity, isPaired, loadIdentity } from '../services/server-identity';

export const pairingRouter = Router();

interface PairBody {
  code?: string;
  name?: string;
  publicUrl?: string;
}

/// Detect a sensible self-URL for the library_servers row, defaulting to
/// the same hostname:port the request came in on. Operator can override
/// via PUBLIC_URL env var (e.g. for behind-tunnel deployments) or via the
/// `publicUrl` field in the pair POST body.
function detectSelfUrl(req: Request): string {
  if (process.env.PUBLIC_URL) return process.env.PUBLIC_URL;
  const proto = (req.headers['x-forwarded-proto'] as string) ?? req.protocol;
  const host = (req.headers['x-forwarded-host'] as string) ?? req.get('host');
  return `${proto}://${host}`;
}

/// POST /pair  body: { code, name?, publicUrl? }
/// CLI / wizard claims a 6-digit pairing code generated by the user via
/// the app. Idempotent: if already paired, returns the existing identity.
pairingRouter.post('/pair', async (req: Request, res: Response) => {
  if (!hubConfigured()) {
    res.status(503).json({
      success: false,
      error: 'SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY must be set in env first.',
    });
    return;
  }

  if (isPaired()) {
    res.status(200).json({
      success: true,
      data: { paired: true, identity: loadIdentity() },
    });
    return;
  }

  const body = (req.body ?? {}) as PairBody;
  const code = (body.code ?? '').trim();
  if (!/^[0-9]{6}$/.test(code)) {
    res.status(400).json({ success: false, error: 'code must be 6 digits' });
    return;
  }

  const name = (body.name ?? '').trim() || `${os.hostname()}'s library`;
  const url = (body.publicUrl ?? '').trim() || detectSelfUrl(req);

  try {
    const hub = hubClient();
    // Look up the pairing — RLS lets the service role read any row.
    const { data: pairing, error: lookupErr } = await hub
      .from('library_server_pairings')
      .select('*')
      .eq('code', code)
      .maybeSingle();
    if (lookupErr) throw lookupErr;
    if (!pairing) {
      res.status(404).json({ success: false, error: 'No pairing for that code' });
      return;
    }
    if (pairing.consumed_at) {
      res.status(409).json({ success: false, error: 'Code already used' });
      return;
    }
    if (new Date(pairing.expires_at) < new Date()) {
      res.status(410).json({ success: false, error: 'Code expired — generate a new one in the app' });
      return;
    }

    // Insert the library_servers row.
    const { data: server, error: insertErr } = await hub
      .from('library_servers')
      .insert({
        owner_id: pairing.claimer_user_id,
        name,
        url,
        platform: process.platform,
        version: '0.6.0',
      })
      .select()
      .single();
    if (insertErr) throw insertErr;

    // Mark pairing consumed.
    await hub
      .from('library_server_pairings')
      .update({ consumed_at: new Date().toISOString(), consumed_by_server_id: server.id })
      .eq('code', code);

    // Save identity locally — survives restarts.
    saveIdentity({
      serverId: server.id,
      ownerId: pairing.claimer_user_id,
      serverName: name,
      pairedAt: new Date().toISOString(),
    });

    res.status(201).json({
      success: true,
      data: { paired: true, server_id: server.id, server_name: name, url },
    });
  } catch (err) {
    // Surface the underlying error in logs + response while we're
    // bringing up the federation flow.
    console.error('[pair] failed', err);
    let detail = 'Pairing failed';
    if (err instanceof Error) detail = err.message;
    else if (err && typeof err === 'object') {
      try { detail = JSON.stringify(err); } catch { /* */ }
    }
    res.status(500).json({ success: false, error: detail });
  }
});

/// GET /pair/status — used by the wizard to poll for completion (or the
/// app, for a real-time check before opening books from this server).
pairingRouter.get('/pair/status', (req: Request, res: Response) => {
  res.json({
    success: true,
    data: {
      hub_configured: hubConfigured(),
      paired: isPaired(),
      identity: loadIdentity(),
    },
  });
});
